### ISSUE TITLE
How to correctly use the tag ":v0.0.0"

### ISSUE THREAD

**Issue by CleverMindDev** [yobasystems/alpine-mariadb#12]
By checking the documentation
> Tags
>  :latest, :amd64 latest branch based on amd64
>  :master master branch usually inline with latest
>  :v0.0.0 version number related to mariadb version
>  :armhf, :arm32v7 Armv7 based on latest tag but arm architecture

I am trying to specify the tag ":vX.X.X" as described in the documentation to build the correct image for the desired mariadb version.

For example I am using in the Dockerfile:
```
FROM yobasystems/alpine-mariadb:v10.2.15
...etc...
```
However it fails.

The only working tags are the ones described [here](https://hub.docker.com/r/yobasystems/alpine-mariadb/tags/)

Am I doing something wrong ?

**Comment by dominictayloruk** [comment]
No it's just the auto tagging doesn't work on the quay.io and dockerhub automated builds.

Also if the versions become stale, old or unsupported or contain vulnerabilities then I usually delete them. Maybe I will tag the last two versions and maybe also implement a :stable tag.

**Comment by KingRial** [comment]
It would be nice to be able to use at least a ":stable" tag.

For example, right now the current "latest" image has a big issue:
https://github.com/yobasystems/alpine-mariadb/issues/24

And there is no way to use easily previous stable images

**Comment by dominictayloruk** [comment]
Next on the list. Manifest creation for auto arch version tag coming soon.

**Comment by dominictayloruk** [comment]
Think this is sorted.

Both `:stable` and `:10.3.16` are available now. Going forward with new versions they should be tagged and the old ones left for historical reasons unless there are multiple security vulnerabilities, in which case i'll delete the tags.
