### ISSUE TITLE
Not passing parameters to mysqld

### ISSUE THREAD

**Issue by keithy** [yobasystems/alpine-mariadb#13]
Using the official mariadb imagesIt is useful to pass some parameters to mysqld as described:

https://docs.docker.com/samples/library/mariadb/ in the section titled 
"Configuration without a cnf file"

This can be used from a docker-compose-file like so:

    command:
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --explicit-defaults-for-timestamp=1

So I assume you just need: exec /usr/bin/mysqld --user=mysql --console $@

**Comment by xgenvn** [comment]
I think this also the reason I cannot set default timezone directly to the command.

**Comment by dominictayloruk** [comment]
Merged with https://github.com/yobasystems/alpine-mariadb/commit/cb4a998770afe15c38ab337ac7a1bf0aa4f38d98

Thanks [keithy](https://github.com/keithy)

**Comment by keithy** [comment]
Great!
