### ISSUE TITLE
Automatic architecture selection?

### ISSUE THREAD

**Issue by keithy** [yobasystems/alpine-mariadb#15]
Any chance of making the architecture selection automatic for :latest ?

**Comment by dominictayloruk** [comment]
It needs a manifest file for that. If you know how this could be done I could find some time to automate it with gitlab ci

https://gitlab.com/gitlab-org/gitlab-ce/issues/40197#note_94416667

**Comment by dominictayloruk** [comment]
I will take a look

**Comment by dominictayloruk** [comment]
```:latest``` tag now has manifest on dockerhub but not on quay as it's not compatible.

This will enable auto arch selection.
