### ISSUE TITLE
Start fails after 9 november update

### ISSUE THREAD

**Issue by BudBundi** [yobasystems/alpine-mariadb#18]
arm32v7 image with mounted database

log is saying:
/scripts/run.sh: wait: line 89: Illegal number: 
SQL init process failed.
[i] mysqld already present, skipping creation
[i] MySQL directory already present, skipping creation
/scripts/run.sh: wait: line 89: Illegal number: 
SQL init process failed.
/scripts/run.sh: ignoring /docker-entrypoint-initdb.d/*

**Comment by BudBundi** [comment]
I got it to run when I comment out this part:

if ! kill -s TERM "$pid" || ! wait "$pid"; then
		echo >&2 'MySQL init process failed.'
		exit 1
fi

**Comment by rouing** [comment]
Aye, I have same issue.

**Comment by BudBundi** [comment]
Not fixed with last commit now:
[i] mysqld not found, creating....
[i] MySQL directory already present, skipping creation
/scripts/run.sh: ignoring /docker-entrypoint-initdb.d/*
/scripts/run.sh: line 92: _get_config: not found
/scripts/run.sh: line 93: --skip-networking: not found
SQL init process failed.

**Comment by dominictayloruk** [comment]
removing the pid section, needs some further analysis to work. Lets me just try and get the container back in a working state.

**Comment by BudBundi** [comment]
With the last update, the container start again, so I close the issue
