### ISSUE TITLE
mariadb failing to create a new user

### ISSUE THREAD

**Issue by garza** [yobasystems/alpine-mariadb#2]
using the docker-compose example, when doing an initial docker-compose up, the run.sh fails to create the database and user (root is created ok with a random password).  I also can't seem to connect to mariadb with the root password (i'm using expose 3306) from the host.

on the initial run, i do see in the script an error:

```
mariadb_1    | 2017-06-13 16:22:23 140096404945736 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1    | ERROR: 1133  Can't find any matching row in the user table
mariadb_1    | 2017-06-13 16:22:23 140096404945736 [ERROR] Aborting
mariadb_1    | 

```

**Comment by dominictayloruk** [comment]
I haven't had a chance to diagnose this yet, sorry. Maybe a recent version has fixed the issue.

**Comment by garza** [comment]
no worries, pretty sure this was address in 52fb9f8f7c46dcb8690a732fa64df131c5a20976
