### ISSUE TITLE
Stable versioning

### ISSUE THREAD

**Issue by blackandred** [yobasystems/alpine-mariadb#25]
Hi,

I think it may be a good idea to keep tags like on the original MariaDB image eg. 13.2, 13.2.1, latest. What do you think?

**Comment by blackandred** [comment]
It may be a little bit related to https://github.com/yobasystems/alpine-mariadb/issues/15

**Comment by dominictayloruk** [comment]
There are tags on quay & gitlab just not on the dockerhub. I'm unsure on the regex to generate tags in an automated build on dockerhub.

**Comment by dominictayloruk** [comment]
Maybe the current 10.3.12 can be tagged stable now most of the problems have been resolved

**Comment by blackandred** [comment]
:+1:

**Comment by dominictayloruk** [comment]
Finally tag the stable release. Enjoy `:stable`
