### ISSUE TITLE
views are not granted to default user

### ISSUE THREAD

**Issue by MartinMuzatko** [yobasystems/alpine-mariadb#31]
When creating a DB using init scripts, the TABLEs can be accessed by the user created with environment variables. However, the VIEWs are not accessible.

Can someone reproduce this?

Thanks!

**Comment by MartinMuzatko** [comment]
I found the problem, it was related to how the initdb scripts are executed. I documented that here already: #29 

However, if I use the `USE` statement, the privileges are not assigned correctly.

**Comment by dominictayloruk** [comment]
I can't reproduce, although i'm not entirely sure i understand you.

**Comment by dominictayloruk** [comment]
Did you manage to resolve the issue?

**Comment by MartinMuzatko** [comment]
I can't remember actually that much, but looks like we don't have that problem anymore. I'll open again when I have a reproducible build. 👍  thanks
