### ISSUE TITLE
Timezone ?

### ISSUE THREAD

**Issue by meandus** [yobasystems/alpine-mariadb#33]
Hi,

impossible to change TZ on docker-compose using environnement variable:

    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      **TZ: "Europe/Paris"**

How is it possible to do this action ?

**Comment by dominictayloruk** [comment]
Yes this is possible, let me have a look.

More information is here https://mariadb.com/kb/en/library/time-zones/

**Comment by dominictayloruk** [comment]
Try using an offset like  +5:00 or -9:00

Also check the host has the correct timezone as it should get this info from the system.

**Comment by dominictayloruk** [comment]
Failing all of that you would need to edit the run command and add
`--default-time-zone='Europre/Paris'`

`exec /usr/bin/mysqld --user=mysql --console --skip-name-resolve --skip-networking=0 --default-time-zone='Europre/Paris'`

**Comment by ekiel** [comment]
is it possible to have this in a docker-compose variable?
