### ISSUE TITLE
update to 10.4.13

### ISSUE THREAD

**Issue by ismkdc** [yobasystems/alpine-mariadb#37]
please upgrade mariadb db to 10.4.13

**Comment by dominictayloruk** [comment]
Yes i will, i can see here it was built 3 days ago https://pkgs.alpinelinux.org/packages?name=mariadb&branch=v3.11

I'm just in the process of setting up a new Raspberry pi 4 k3s cluster to run the arm32 & arm64 builds on as currently the arm64 builds are run on Scaleway arm which pose a couple of limitions;

- They are shortly to be end of life https://www.scaleway.com/en/docs/migrate-c2-arm64-to-virtual-instance-using-rsync/
- They can only run 64-bit arm binaries https://en.wikichip.org/wiki/cavium/thunderx

**Comment by dominictayloruk** [comment]
Source done, builds will be later on today 💯

**Comment by ismkdc** [comment]
Thank you for quick upgrade but docker hub still seems not upgraded :(

**Comment by dominictayloruk** [comment]
Cluster all ready, raspberry's building arm32 & arm64 images. 

Quay.io is having some issues so it's stopping the build from completing but as soon as there all back online i'll rerun the builds to complete the manifests.
https://status.quay.io/incidents/kw2627bsdwd9

**Comment by ismkdc** [comment]
its looks like resolved

**Comment by dominictayloruk** [comment]
All done, new builds should come a little quicker now the new cluster is in place.
