### ISSUE TITLE
where is the standard mysql.cnf file in this docker instance?

### ISSUE THREAD

**Issue by gitmko0** [yobasystems/alpine-mariadb#38]
where is the standard mysql.cnf file in this docker instance?

**Comment by dominictayloruk** [comment]
The configuration file is located;

`/etc/my.cnf` 

--> which in turn references the directory `/etc/my.cnf.d/` 

--> contains the file `/etc/my.cnf.d/mariadb-server.cnf`

**Comment by michabrey** [comment]
I tried to find the file in the locations you mentioned, but I can't find them. What variable would I have to put into the docker-composer file to access my.cnf? or mariadb-server.cnf?
