### ISSUE TITLE
create sql dump

### ISSUE THREAD

**Issue by centralhardware** [yobasystems/alpine-mariadb#39]
How to create dump from container

**Comment by dominictayloruk** [comment]
More info here;
  - https://mariadb.com/kb/en/backup-and-restore-overview/
  - https://mariadb.com/kb/en/mariabackup/
  - https://mariadb.com/kb/en/making-backups-with-mysqldump/

Mariabackup is preffered as it is a fork of Percona Xtra backup and should be compatible with this container as it is installed with the mariadb package https://pkgs.alpinelinux.org/package/v3.12/main/x86_64/mariadb-backup
