### ISSUE TITLE
Docker-Compose Mapped volumes in host uid=systemd-timesync / gp=input. Backups with root pwd fails.

### ISSUE THREAD

**Issue by JayAr-ZA** [yobasystems/alpine-mariadb#4]
Hi, by starting up the MAriaDB with a docker-compose, and mapping a folder on the docker host where the db is to be stored, it runs, but the host folders ownership changes, to systemd-timesync / input.

the result of this is that I cannot backup the db with mysqldump command with root, as it does not have rights to the folder where the DB is now mounted.

Others reports the same problem on other docker images, with several fixes. [This guy](https://github.com/nginxinc/docker-nginx/issues/113) proposes to do a chmod after creation of the volume, or adding another user for the docker mariadb client.

Am I doing something wrong, or is this something you could add?

Thank you for a great image !

**Comment by dominictayloruk** [comment]
I'll have to take a closer look at this.

**Comment by dominictayloruk** [comment]
This is because you have host id & container id conflicts
