### ISSUE TITLE
Please upgrade

### ISSUE THREAD

**Issue by ismkdc** [yobasystems/alpine-mariadb#41]
hello,
may u upgrade to latest version mariadb (10.4.14) it has been released at repo https://pkgs.alpinelinux.org/package/edge/main/x86/mariadb

**Comment by dominictayloruk** [comment]
Its not on edge its a stable branch which you can find here;
https://pkgs.alpinelinux.org/packages?name=mariadb&branch=v3.12

Also this is the second time you've opened an issue when there isn't an issue.
