### ISSUE TITLE
Inoperable on ZFS Hosts

### ISSUE THREAD

**Issue by Aquilum** [yobasystems/alpine-mariadb#44]
It appears that this container is using a version of MariaDB that attempts to use fallocate(...) on all Linux systems - which will fail if the host FS doesn't support that (ZFS being a notable case).

Upstream issue tracker suggests this is resolved if you take a later MariaDB build: https://jira.mariadb.org/browse/MDEV-16015

Confirmed using an alternative 10.5.8 build works for my deployment.

**Comment by dominictayloruk** [comment]
I will try to update all the images over the course of the next few days, been really busy recently so all the repos have been suffering a little neglect.

**Comment by dominictayloruk** [comment]
Sorry for the delay, i've updated the image to Alpine 3.13.5 & MariaDB version 10.5.8

**Comment by Aquilum** [comment]
Awesome, thanks!
