### ISSUE TITLE
100% CPU utilization since latest update on armhf

### ISSUE THREAD

**Issue by TheNymon** [yobasystems/alpine-mariadb#48]
Seems like MariaDB has some issues running on Alpine Version 3.13.5 after upgrading
Every database instance I'm running on a Container each uses 100% of the CPU core

**Comment by dominictayloruk** [comment]
SEE https://github.com/yobasystems/alpine-mariadb/issues/47

**Comment by TheNymon** [comment]
Thank you
I noticed too late
