### ISSUE TITLE
Econnrefused error and 

### ISSUE THREAD

**Issue by deboy69** [yobasystems/alpine-mariadb#49]
getting the following errors

[4/25/2021] [11:48:04 AM] [Global   ] › ✖  error     connect ECONNREFUSED 172.22.0.2:3306

and

[i] mysqld not found, creating....

[i] MySQL data directory not found, creating initial DBs

233980-03-27 11:18:17 0 [ERROR] This MySQL server doesn't support dates later than 2038

 Creating database: npm

[i] with character set: 'utf8' and collation: 'utf8_general_ci'

[i] Creating user: npm with password xxxxxxx

275081-09-13 20:01:08 0 [ERROR] This MySQL server doesn't support dates later than 2038

/scripts/run.sh: ignoring or entrypoint initdb empty /docker-entrypoint-initdb.d/*

MySQL init process done. Ready for start up.

exec /usr/bin/mysqld --user=mysql --console --skip-name-resolve --skip-networking=0

515981-12-18  5:22:21 0 [ERROR] This MySQL server doesn't support dates later than 2038

[i] mysqld already present, skipping creation

[i] MySQL data directory not found, creating initial DBs

**Comment by AngelKing86** [comment]
Hi,

i getting the same erros on yobasystems/alpine-mariadb:arm32v7

[i] mysqld not found, creating....
[i] MySQL directory already present, skipping creation
230304-02-25 21:24:18 0 [ERROR] This MySQL server doesn't support dates later than 2038
[i] mysqld already present, skipping creation
[i] MySQL directory already present, skipping creation
432100-11-20 11:39:44 0 [ERROR] This MySQL server doesn't support dates later than 2038
[i] mysqld already present, skipping creation
[i] MySQL directory already present, skipping creation
117310-11-29  4:43:03 0 [ERROR] This MySQL server doesn't support dates later than 2038
[i] mysqld already present, skipping creation
[i] MySQL directory already present, skipping creation

**Comment by AngelKing86** [comment]
> Hi,
> 
> i getting the same erros on yobasystems/alpine-mariadb:arm32v7
> 
> [i] mysqld not found, creating....
> [i] MySQL directory already present, skipping creation
> 230304-02-25 21:24:18 0 [ERROR] This MySQL server doesn't support dates later than 2038
> [i] mysqld already present, skipping creation
> [i] MySQL directory already present, skipping creation
> 432100-11-20 11:39:44 0 [ERROR] This MySQL server doesn't support dates later than 2038
> [i] mysqld already present, skipping creation
> [i] MySQL directory already present, skipping creation
> 117310-11-29 4:43:03 0 [ERROR] This MySQL server doesn't support dates later than 2038
> [i] mysqld already present, skipping creation
> [i] MySQL directory already present, skipping creation

Workaround: Downgrade to yobasystems/alpine-mariadb:10.4.17-arm32v7 has resolved the issue

**Comment by dominictayloruk** [comment]
https://github.com/yobasystems/alpine-mariadb/issues/47
