### ISSUE TITLE
MySQL root password without dollar symbol

### ISSUE THREAD

**Issue by olegstepura** [yobasystems/alpine-mariadb#5]
Hi!

Didn't dig deep, but it seems like a dollar sign is missing here (`MYSQL_ROOT_PASSWORD` => `$MYSQL_ROOT_PASSWORD`):

https://github.com/yobasystems/alpine-mariadb/blob/01cd8d0fcf13ba216da6ffa759efd1257b77cbbc/alpine-mariadb-amd64/files/run.sh#L48

**Comment by dominictayloruk** [comment]
Fixed, Thanks for spotting this.
