### ISSUE TITLE
Versioning and Tags

### ISSUE THREAD

**Issue by tflori** [yobasystems/alpine-mariadb#52]
This looks like a widely accepted image for mariadb on alpine linux. Unfortunately it lacks some versioning tags. It is not recommended to use `:latest` tag as it might fail when a newer version is released. Instead you should use a specific version.

But this image has only 10.5.9, 10.5.8 etc... When I'm using 10.5.9 now and there is a security issue in 10.5.9 I will not get an update to 10.5.10 until I change the used tag. My suggestion is to tag every image 3 times: `:10.5.9` would get `:10.5` and `:10` to have `:10` as the latest version of major release 10 and `:10.5` as the latest version of minor release 10.5.

I'm doing something similar for my images and I'm happy to provide a PR if you like to have this feature too.

**Comment by dominictayloruk** [comment]
Should be done.
