### ISSUE TITLE
One core 100% used constantly

### ISSUE THREAD

**Issue by module0x90** [yobasystems/alpine-mariadb#55]
Since an earlier version, couple of months back I have this container using 1 core only. I am using Nextcloud and that doesn't work as it can't talk to the DB.

Inside the container (RPi 4B) I can see

Mem: 5508532K used, 2555748K free, 301724K shrd, 159588K buff, 4897740K cached
CPU:   2% usr  24% sys   0% nic  73% idle   0% io   0% irq   0% sirq
Load average: 1.01 1.56 1.69 2/359 16
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 root     R    30368   0%   3  25% /usr/bin/mysqld --user=mysql --console --skip-name-resolve --skip-networking=0 --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    9     0 root     S     1744   0%   2   0% /bin/sh
   16     9 root     R     1708   0%   1   0% top

Outside - it is shown as 100% CPU.

When I do an strace outside the container of the process inside as root:

syscall_0x193(0x6, 0xbea169d0, 0x6, 0xe40e7c, 0xc91521a4, 0) = -1 EPERM (Operation not permitted)
syscall_0x193(0x6, 0xbea169d0, 0x6, 0xe40e7c, 0, 0) = -1 EPERM (Operation not permitted)
syscall_0x193(0x6, 0xbea169d0, 0x6, 0xe40e7c, 0xc91521a4, 0) = -1 EPERM (Operation not permitted)
syscall_0x193(0x6, 0xbea169d0, 0x6, 0xe40e7c, 0, 0) = -1 EPERM (Operation not permitted)

Seems to be related with
https://forum.armbian.com/topic/13737-focal-continously-changing-system-time/
https://github.com/Mailu/Mailu/issues/1752

This container was working just fine at some point... suddenly it was always on 100% and never responds.

Linux docker 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
Raspbian Buster, up2date, no updates outstanding.

Any thoughts?

**Comment by dominictayloruk** [comment]
32bit kernel on Raspberry Pi 4??

```
Linux docker 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
```

Use a 64bit kernel. Problem solved

**Comment by dominictayloruk** [comment]
See here https://github.com/yobasystems/alpine-mariadb/issues/47

**Comment by module0x90** [comment]
Sorry, 
I changed that the system is having a 64bit kernel. After that alpine-mariadb still showed the same behaviour, and strace was identical. I managed to change the image to the aarch64, but that this continously restarting, probably due to the fact that my system is still 32.

Any advice please?
