### ISSUE TITLE
Cannot start on Raspberry Pi

### ISSUE THREAD

**Issue by RomainTT** [yobasystems/alpine-mariadb#57]
Hello,

Since version `10.5.8`, the image does not run correctly on my [Raspberry Pi 4](https://www.raspberrypi.org/products/raspberry-pi-4-model-b/).

The container stops with the following error:

```
This MySQL server doesn't support dates later than 2038
```

Indeed, when I run the command `date` in a shell in this container, I got a series of numbers with no meaning. When I run this same command on version `10.4.17`, I get a correct date string.

I don’t know why but there is a problem with time since that version.

**Comment by MartyLake** [comment]
You have to also mount as a volume `      - /etc/localtime:/etc/localtime:ro`
I found this trick from https://thingsiforgetblog.wordpress.com/2019/03/30/docker-compose-yaml-examples/

**Comment by dominictayloruk** [comment]
Or just run `yobasystems/alpine-mariadb:10.5.9`

If you are on a raspberry pi 4, then using a 64bit os mitigates this problem also. Only affected systems are 32bit.

**Comment by dominictayloruk** [comment]
Also see here as it has already been discussed.

https://github.com/yobasystems/alpine-mariadb/issues/47

**Comment by RomainTT** [comment]
Thank you, I didn’t see #47, I should be able to make it work then.
