### ISSUE TITLE
Any updates soon?

### ISSUE THREAD

**Issue by hakoptak** [yobasystems/alpine-mariadb#59]
Hi Dominic,

I really like this image but I am wondering if you will be updating to Alpine 3.15 and MariaDB 10.7.3 soon... Your sites seem be be offline which worries me a bit. Hope you're fine!

**Comment by dominictayloruk** [comment]
I'll try before the weekend if I can update all images. They are long overdue

**Comment by hakoptak** [comment]
Thanks for following up. Good to hear from you!

**Comment by dominictayloruk** [comment]
Updated to Alpine 3.15.0 & MariaDB 10.6.4
