### ISSUE TITLE
[Note] /usr/bin/mysqld (initiated by: unknown): Normal shutdown

### ISSUE THREAD

**Issue by Trilokkumar1** [yobasystems/alpine-mariadb#69]
I am using using same code to deploy MarioDB but when I restart the container it keeps going shutdown

**Comment by dominictayloruk** [comment]
Probably your host. Where are you running the container? Whats the hardware? Where are your files stored?

**Comment by Trilokkumar1** [comment]
> Probably your host. Where are you running the container? Whats the hardware? Where are your files stored?

Running in SUSE SP12 .

**Comment by dominictayloruk** [comment]
Do you still have the issue? Did you resolve the issue?

Going to close but reopen if you feel the need, probably a host issue.
