### ISSUE TITLE
MariaDB 11.0.x

### ISSUE THREAD

**Issue by SoulInfernoDE** [yobasystems/alpine-mariadb#70]
Could you update your alpine image to MariaDB 11 as there seems to be a stable release now.

Thank you :heart: 

https://hub.docker.com/layers/library/mariadb/11.0.2/images/sha256-c57215c3aabbdb96353ce8b89a7bd6be089f49a4d6bb37f199288a1bf0438a02?context=explore

Careful with version 11.1.x and 11.2.x as these are non stable versions yet.

**Comment by dominictayloruk** [comment]
https://pkgs.alpinelinux.org/packages?name=mariadb&branch=v3.18&repo=&arch=&maintainer=

**Comment by SoulInfernoDE** [comment]
Oh I was thinking you did compile from source, does this work yet?

https://mariadb.com/kb/en/building-mariadb-from-source-using-musl-based-gnulinux/

https://github.com/MariaDB/server/releases/tag/mariadb-11.0.2

**Comment by SoulInfernoDE** [comment]
@dominictayloruk

I digged into it myself and could successfully build mariadb-11.0.2 :hammer_and_wrench:  on alpine.

If you like you can adapt the files for example to a testing branch of mariadb-11 yourself. 

:link: https://github.com/SoulInfernoDE/dockerfiles/releases

I only changed the version number to 11.0.2 in the [APKBUILD](https://git.alpinelinux.org/aports/commit/?id=06fb7a271a3460d7cbf4a08abaf9c52461d2a2b8) file :memo:

**Comment by dominictayloruk** [comment]
👍👍👍
