### ISSUE TITLE
'arm32v7' OS/ARCH info states 'linux/arm64'

### ISSUE THREAD

**Issue by stheine** [yobasystems/alpine-mariadb#71]
https://hub.docker.com/r/yobasystems/alpine-mariadb/tags?page=1&name=arm32v7&ordering=last_updated

I'm filtering for `arm32v7` since I'm running on an older ARM32 system.
while starting the alpine-mariadb, there is a warning:
`The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested`

and I think that might be related to the 'OS/ARCH' information on docker hub that states `linux/arm64`
![image](https://github.com/yobasystems/alpine-mariadb/assets/19614566/8f88cd3f-524a-49a4-a7c1-5afe66eb57ce)

it looks incorrect, that an `arm32` build is flagged as `arm64`.

**Comment by dominictayloruk** [comment]
Looks like the ci needed to add the `--platform` flag.
Adding `--platform linux/arm/v7` seems to have resolved it, i will push new images shortly.

**Comment by dominictayloruk** [comment]
https://github.com/yobasystems/gitlab-runner/issues/4

**Comment by dominictayloruk** [comment]
New images should be available soon, got to wait 6 hours for my docker hub account rate limits to reset then they should be online and ready to test.

**Comment by dominictayloruk** [comment]
Manifests complete on dockerhub, should correctly pull now.

**Comment by stheine** [comment]
thanks, I can confirm the fix.
