### ISSUE TITLE
Table '/tmp/#sql_1_0.MAI' is read only

### ISSUE THREAD

**Issue by ivixq** [yobasystems/alpine-mariadb#8]
When I ran the image In CentOS 7.3 , the error happened.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| test               |
+--------------------+
4 rows in set (0.00 sec)

MariaDB [(none)]> use mysql;
Database changed
MariaDB [mysql]> desc user;
ERROR 1036 (HY000): Table '/tmp/#sql_1_0.MAI' is read only

**Comment by ivixq** [comment]
#!/usr/bin/with-contenv bash

su-exec mysql mysqld_safe

**Comment by dominictayloruk** [comment]
Unsure as my docker hosts are usually Alpine, Debian or Ubuntu. Maybe someone else might be more knowledgeable.

**Comment by CleverMindDev** [comment]
Just got the same error and it could be related to the following infos:
https://stackoverflow.com/questions/44008880/table-tmp-sql-1-0-mai-is-read-only

Hope it could help!
